baseurl = "./"
title = "OpenPitrix"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[languages]
[languages.en]
  languageCode = "en-us"
  footer = "&copy; [openpitrix.io](https://openpitrix.io) 2017 | [Github](https://github.com/openpitrix) | [Gitee](https://gitee.com/openpitrix)"
[[languages.en.menu.main]]
    name = "OpenPitrix"
    url = "/en/"
    weight = 1
[[languages.en.menu.main]]
    name = "Features"
    url = "/en/features/"
    weight = 2
[[languages.en.menu.main]]
    name = "Case Studies"
    url = "/en/cases/"
    weight = 3
[[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 4

[languages.zh]
  languageCode = "zh-cn"
  footer = "&copy; [openpitrix.io](https://openpitrix.io) 2017 | [Github](https://github.com/openpitrix) | [码云](https://gitee.com/openpitrix)"
[[languages.zh.menu.main]]
    name = "OpenPitrix"
    url = "/zh/"
    weight = 1
[[languages.zh.menu.main]]
    name = "特性"
    url = "/zh/features"
    weight = 2
[[languages.zh.menu.main]]
    name = "案例"
    url = "/zh/cases"
    weight = 3
[[languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about"
    weight = 4

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
[params]
    description = "A website built through Hugo and blogdown."

